import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Brain, RefreshCw, Download, AlertCircle } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";

interface AIAnalysisResponse {
  success: boolean;
  report: string;
  sensorData: {
    timestamp: string;
    vitalSigns: {
      heartRate: string;
      spo2: string;
      bloodPressure: string;
      temperature: string;
      respiratoryRate: string;
    };
  };
  generatedAt: string;
}

export default function AIAnalysisPage() {
  const userId = localStorage.getItem("userId");
  const [generatedReport, setGeneratedReport] = useState<AIAnalysisResponse | null>(null);

  const { mutate: generateAnalysis, isPending, error } = useMutation<AIAnalysisResponse>({
    mutationFn: async () => {
      const token = localStorage.getItem("authToken");
      if (!token) {
        throw new Error("Authentication required");
      }

      const response = await fetch("/api/ai-analysis", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ userId }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || "Failed to generate analysis");
      }

      return response.json();
    },
    onSuccess: (data) => {
      setGeneratedReport(data);
    },
  });

  const handleDownload = () => {
    if (!generatedReport) return;

    const content = `
AI-GENERATED HEALTH REPORT
Generated: ${new Date(generatedReport.generatedAt).toLocaleString()}
Data Timestamp: ${new Date(generatedReport.sensorData.timestamp).toLocaleString()}

VITAL SIGNS AT TIME OF ANALYSIS:
- Heart Rate: ${generatedReport.sensorData.vitalSigns.heartRate}
- SpO2: ${generatedReport.sensorData.vitalSigns.spo2}
- Blood Pressure: ${generatedReport.sensorData.vitalSigns.bloodPressure}
- Temperature: ${generatedReport.sensorData.vitalSigns.temperature}
- Respiratory Rate: ${generatedReport.sensorData.vitalSigns.respiratoryRate}

${"=".repeat(60)}

${generatedReport.report}

${"=".repeat(60)}
Generated by Health Monitor AI Analysis System
This report is for informational purposes only and should not replace professional medical consultation.
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `health-report-${new Date(generatedReport.generatedAt).toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Format markdown-like content for display
  const formatReport = (report: string) => {
    const lines = report.split("\n");
    const formatted = lines.map((line, index) => {
      // Handle headers
      if (line.startsWith("## ")) {
        return (
          <h2 key={index} className="text-2xl font-bold mt-8 mb-4 text-foreground border-b pb-2">
            {line.replace("## ", "")}
          </h2>
        );
      }
      if (line.startsWith("### ")) {
        return (
          <h3 key={index} className="text-xl font-semibold mt-6 mb-3 text-foreground">
            {line.replace("### ", "")}
          </h3>
        );
      }
      if (line.startsWith("**") && line.endsWith(":**")) {
        return (
          <h4 key={index} className="text-lg font-semibold mt-4 mb-2 text-foreground">
            {line.replace(/\*\*/g, "")}
          </h4>
        );
      }
      // Handle bullet points
      if (line.trim().startsWith("- ")) {
        return (
          <li key={index} className="ml-4 mb-1 text-muted-foreground">
            {line.trim().substring(2)}
          </li>
        );
      }
      // Handle numbered lists
      if (/^\d+\.\s/.test(line.trim())) {
        return (
          <li key={index} className="ml-4 mb-1 text-muted-foreground list-decimal">
            {line.trim().substring(line.trim().indexOf(" ") + 1)}
          </li>
        );
      }
      // Handle bold text
      if (line.includes("**")) {
        const parts = line.split(/(\*\*[^*]+\*\*)/g);
        return (
          <p key={index} className="mb-2 text-muted-foreground">
            {parts.map((part, i) =>
              part.startsWith("**") && part.endsWith("**") ? (
                <strong key={i} className="font-semibold text-foreground">
                  {part.replace(/\*\*/g, "")}
                </strong>
              ) : (
                part
              )
            )}
          </p>
        );
      }
      // Regular paragraphs
      if (line.trim()) {
        return (
          <p key={index} className="mb-3 text-muted-foreground leading-relaxed">
            {line}
          </p>
        );
      }
      return <br key={index} />;
    });

    return <div className="space-y-2">{formatted}</div>;
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <Brain className="h-8 w-8 text-primary" />
            <h1 className="text-3xl font-bold text-foreground">AI Health Analysis</h1>
          </div>
          <p className="text-muted-foreground">
            Get AI-powered comprehensive health reports based on your real-time vital signs data
          </p>
        </div>
        <Button
          onClick={() => generateAnalysis()}
          disabled={isPending}
          className="gap-2"
          size="lg"
        >
          {isPending ? (
            <>
              <RefreshCw className="h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : generatedReport ? (
            <>
              <RefreshCw className="h-4 w-4" />
              Regenerate Report
            </>
          ) : (
            <>
              <Brain className="h-4 w-4" />
              Generate Report
            </>
          )}
        </Button>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>
            {error instanceof Error ? error.message : "Failed to generate analysis. Please try again."}
          </AlertDescription>
        </Alert>
      )}

      {isPending ? (
        <Card className="p-8">
          <div className="space-y-4">
            <Skeleton className="h-8 w-64" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-5/6" />
            <Skeleton className="h-8 w-64 mt-8" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-4/5" />
            <Skeleton className="h-4 w-3/4" />
          </div>
        </Card>
      ) : generatedReport ? (
        <div className="space-y-4">
          {/* Report Header with Meta Info */}
          <Card className="p-4 bg-muted/50">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-4">
                <Badge variant="outline" className="gap-2">
                  <Brain className="h-3 w-3" />
                  AI Generated
                </Badge>
                <span className="text-sm text-muted-foreground">
                  Generated: {new Date(generatedReport.generatedAt).toLocaleString()}
                </span>
              </div>
              <div className="flex items-center gap-4">
                <span className="text-sm text-muted-foreground">
                  Data from: {new Date(generatedReport.sensorData.timestamp).toLocaleString()}
                </span>
                <Button
                  onClick={handleDownload}
                  variant="outline"
                  size="sm"
                  className="gap-2"
                >
                  <Download className="h-4 w-4" />
                  Download Report
                </Button>
              </div>
            </div>
            <div className="mt-4 pt-4 border-t grid grid-cols-2 md:grid-cols-5 gap-4">
              <div>
                <p className="text-xs text-muted-foreground mb-1">Heart Rate</p>
                <p className="text-sm font-semibold">{generatedReport.sensorData.vitalSigns.heartRate}</p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground mb-1">SpO2</p>
                <p className="text-sm font-semibold">{generatedReport.sensorData.vitalSigns.spo2}</p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground mb-1">Blood Pressure</p>
                <p className="text-sm font-semibold">{generatedReport.sensorData.vitalSigns.bloodPressure}</p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground mb-1">Temperature</p>
                <p className="text-sm font-semibold">{generatedReport.sensorData.vitalSigns.temperature}</p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground mb-1">Respiratory Rate</p>
                <p className="text-sm font-semibold">{generatedReport.sensorData.vitalSigns.respiratoryRate}</p>
              </div>
            </div>
          </Card>

          {/* Health Report Content */}
          <Card className="p-8">
            <div className="prose prose-slate dark:prose-invert max-w-none">
              {formatReport(generatedReport.report)}
            </div>
          </Card>

          {/* Disclaimer */}
          <Alert>
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>Important Notice</AlertTitle>
            <AlertDescription>
              This AI-generated health report is based on real-time sensor data and is for informational purposes only. 
              It should not replace professional medical consultation, diagnosis, or treatment. Please consult with a 
              qualified healthcare provider for any medical concerns or before making decisions about your health.
            </AlertDescription>
          </Alert>
        </div>
      ) : (
        <Card className="p-12 text-center">
          <Brain className="h-16 w-16 mx-auto mb-4 text-muted-foreground" />
          <h2 className="text-xl font-semibold mb-2 text-foreground">No Report Generated Yet</h2>
          <p className="text-muted-foreground mb-6">
            Click the "Generate Report" button to create an AI-powered health analysis based on your latest vital signs data.
          </p>
          <Button onClick={() => generateAnalysis()} size="lg" className="gap-2">
            <Brain className="h-4 w-4" />
            Generate Your First Report
          </Button>
        </Card>
      )}
    </div>
  );
}

